package com.jbjares.owlmapper.newmodel.to;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Sun Jan 11 02:43:59 GMT 2015 by jbjares
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.IRLontologies.ie/historicalEvents.owl#Address
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ADDRESS.<p>
     * 
     */
    public static final OWLClass CLASS_ADDRESS = factory.getOWLClass(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#Address"));

    /* ***************************************************
     * Class http://www.IRLontologies.ie/historicalEvents.owl#BirthEvent
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BIRTH_EVENT.<p>
     * 
     */
    public static final OWLClass CLASS_BIRTH_EVENT = factory.getOWLClass(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#BirthEvent"));

    /* ***************************************************
     * Class http://www.IRLontologies.ie/historicalEvents.owl#CauseOfDeath
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CAUSE_OF_DEATH.<p>
     * 
     */
    public static final OWLClass CLASS_CAUSE_OF_DEATH = factory.getOWLClass(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#CauseOfDeath"));

    /* ***************************************************
     * Class http://www.IRLontologies.ie/historicalEvents.owl#County
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COUNTY.<p>
     * 
     */
    public static final OWLClass CLASS_COUNTY = factory.getOWLClass(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#County"));

    /* ***************************************************
     * Class http://www.IRLontologies.ie/historicalEvents.owl#DeathEvent
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DEATH_EVENT.<p>
     * 
     */
    public static final OWLClass CLASS_DEATH_EVENT = factory.getOWLClass(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#DeathEvent"));

    /* ***************************************************
     * Class http://www.IRLontologies.ie/historicalEvents.owl#District
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DISTRICT.<p>
     * 
     */
    public static final OWLClass CLASS_DISTRICT = factory.getOWLClass(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#District"));

    /* ***************************************************
     * Class http://www.IRLontologies.ie/historicalEvents.owl#Event
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class EVENT.<p>
     * 
     */
    public static final OWLClass CLASS_EVENT = factory.getOWLClass(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#Event"));

    /* ***************************************************
     * Class http://www.IRLontologies.ie/historicalEvents.owl#MarriageEvent
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MARRIAGE_EVENT.<p>
     * 
     */
    public static final OWLClass CLASS_MARRIAGE_EVENT = factory.getOWLClass(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#MarriageEvent"));

    /* ***************************************************
     * Class http://www.IRLontologies.ie/historicalEvents.owl#Person
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PERSON.<p>
     * 
     */
    public static final OWLClass CLASS_PERSON = factory.getOWLClass(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#Person"));

    /* ***************************************************
     * Class http://www.IRLontologies.ie/historicalEvents.owl#Place
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PLACE.<p>
     * 
     */
    public static final OWLClass CLASS_PLACE = factory.getOWLClass(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#Place"));

    /* ***************************************************
     * Class http://www.IRLontologies.ie/historicalEvents.owl#Rank
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RANK.<p>
     * 
     */
    public static final OWLClass CLASS_RANK = factory.getOWLClass(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#Rank"));

    /* ***************************************************
     * Class http://www.IRLontologies.ie/historicalEvents.owl#RegisterPage
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class REGISTER_PAGE.<p>
     * 
     */
    public static final OWLClass CLASS_REGISTER_PAGE = factory.getOWLClass(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#RegisterPage"));

    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#DeathCauseOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property DEATH_CAUSE_OF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DEATH_CAUSE_OF = factory.getOWLObjectProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#DeathCauseOf"));

    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#countyOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property COUNTY_OF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_COUNTY_OF = factory.getOWLObjectProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#countyOf"));

    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#deathIsInfBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property DEATH_IS_INFORMED_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DEATH_IS_INFORMED_BY = factory.getOWLObjectProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#deathIsInfBy"));

    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#deathRecordOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property DEATH_RECORD_OF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DEATH_RECORD_OF = factory.getOWLObjectProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#deathRecordOf"));

    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#hasCauseOfDeath
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_CAUSE_OF_DEATH.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_CAUSE_OF_DEATH = factory.getOWLObjectProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#hasCauseOfDeath"));

    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#hasCounty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_COUNTY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_COUNTY = factory.getOWLObjectProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#hasCounty"));

    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#hasDeathRecord
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_DEATH_RECORD.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_DEATH_RECORD = factory.getOWLObjectProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#hasDeathRecord"));

    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#hasInfDeathOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_INFORMED_THE_DEATH_OF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_INFORMED_THE_DEATH_OF = factory.getOWLObjectProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#hasInfDeathOf"));

    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#hasInformant_
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_INFORMANT_.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_INFORMANT_ = factory.getOWLObjectProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#hasInformant_"));

    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#hasRankAtDeath
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_RANK_AT_DEATH.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_RANK_AT_DEATH = factory.getOWLObjectProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#hasRankAtDeath"));

    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#hasRegister
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_REGISTER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_REGISTER = factory.getOWLObjectProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#hasRegister"));

    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#hasRegisterPage
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_REGISTER_PAGE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_REGISTER_PAGE = factory.getOWLObjectProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#hasRegisterPage"));

    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#hasResdAtDeath
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_RESIDENCE_AT_DEATH.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_RESIDENCE_AT_DEATH = factory.getOWLObjectProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#hasResdAtDeath"));

    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#hasResdInfDeath
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_RESIDENCE_DURING_INFORMING_DEATH.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_RESIDENCE_DURING_INFORMING_DEATH = factory.getOWLObjectProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#hasResdInfDeath"));

    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#hasSigned
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_SIGNED.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_SIGNED = factory.getOWLObjectProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#hasSigned"));

    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#informs
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INFORMS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INFORMS = factory.getOWLObjectProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#informs"));

    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#rankPerAtDeath
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property RANK_OF_PERSON_AT_DEATH.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_RANK_OF_PERSON_AT_DEATH = factory.getOWLObjectProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#rankPerAtDeath"));

    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#registerPageOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property REGISTER_PAGE_OF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REGISTER_PAGE_OF = factory.getOWLObjectProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#registerPageOf"));

    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#registeredBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property REGISTERED_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REGISTERED_BY = factory.getOWLObjectProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#registeredBy"));

    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#resdOfPerAtDeath
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property RESIDENCE_OF_PERSON_AT_DEATH.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_RESIDENCE_OF_PERSON_AT_DEATH = factory.getOWLObjectProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#resdOfPerAtDeath"));

    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#resdOfPerInfDeath
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property _RESIDENCE_OF_PERSON_INFORMING_DEATH.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY__RESIDENCE_OF_PERSON_INFORMING_DEATH = factory.getOWLObjectProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#resdOfPerInfDeath"));

    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#signedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property SIGNED_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SIGNED_BY = factory.getOWLObjectProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#signedBy"));

    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/personOntology.owl#OWLObjectPropertyImpl_01420721646860402000
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_DISTRICT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_DISTRICT = factory.getOWLObjectProperty(IRI.create("http://www.IRLontologies.ie/personOntology.owl#OWLObjectPropertyImpl_01420721646860402000"));

    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/personOntology.owl#OWLObjectPropertyImpl_01420721646871238000
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_CHILD.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_CHILD = factory.getOWLObjectProperty(IRI.create("http://www.IRLontologies.ie/personOntology.owl#OWLObjectPropertyImpl_01420721646871238000"));

    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/personOntology.owl#OWLObjectPropertyImpl_01420721646875765000
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_CHILD_OF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_CHILD_OF = factory.getOWLObjectProperty(IRI.create("http://www.IRLontologies.ie/personOntology.owl#OWLObjectPropertyImpl_01420721646875765000"));

    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/personOntology.owl#OWLObjectPropertyImpl_01420721646876718000
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_DISTRICT_OF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_DISTRICT_OF = factory.getOWLObjectProperty(IRI.create("http://www.IRLontologies.ie/personOntology.owl#OWLObjectPropertyImpl_01420721646876718000"));

    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/personOntology.owl#OWLObjectPropertyImpl_01420721646877197000
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_HUSBAND.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_HUSBAND = factory.getOWLObjectProperty(IRI.create("http://www.IRLontologies.ie/personOntology.owl#OWLObjectPropertyImpl_01420721646877197000"));

    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/personOntology.owl#OWLObjectPropertyImpl_01420721646880075000
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_WIFE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_WIFE = factory.getOWLObjectProperty(IRI.create("http://www.IRLontologies.ie/personOntology.owl#OWLObjectPropertyImpl_01420721646880075000"));

    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#AgeAtLastBirthday
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property AGE_AT_LAST_BIRTHDAY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_AGE_AT_LAST_BIRTHDAY = factory.getOWLDataProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#AgeAtLastBirthday"));

    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#CauseIllnessDuration
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CAUSE_OF_DEATH_AND_DURATION_OF_ILLNESS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CAUSE_OF_DEATH_AND_DURATION_OF_ILLNESS = factory.getOWLDataProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#CauseIllnessDuration"));

    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#CondAtDeath
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CONDITION_AT_DEATH.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CONDITION_AT_DEATH = factory.getOWLDataProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#CondAtDeath"));

    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#CountryDesc
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property COUNTRY_DESCIPTION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_COUNTRY_DESCIPTION = factory.getOWLDataProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#CountryDesc"));

    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#InformantQualification
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property QUALIFICATION_OF_INFORMANT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_QUALIFICATION_OF_INFORMANT = factory.getOWLDataProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#InformantQualification"));

    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#StampNum
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property STAMP_NUMBER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_STAMP_NUMBER = factory.getOWLDataProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#StampNum"));

    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#addressDesc
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ADDRESS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ADDRESS = factory.getOWLDataProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#addressDesc"));

    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#cause
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CAUSE_OF_DEATH.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CAUSE_OF_DEATH = factory.getOWLDataProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#cause"));

    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#dateOfDeath
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DATE_OF_DEATH.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DATE_OF_DEATH = factory.getOWLDataProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#dateOfDeath"));

    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#dateOfRegistration
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DATE_OF_REGISTRATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DATE_OF_REGISTRATION = factory.getOWLDataProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#dateOfRegistration"));

    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#datePageCertified
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DATE_OF_PAGE_CERTIFIED.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DATE_OF_PAGE_CERTIFIED = factory.getOWLDataProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#datePageCertified"));

    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#datePageCertifiedAsTrueCopy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DATE_OF_PAGE_CERTIFIED_AS_TRUECOPY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DATE_OF_PAGE_CERTIFIED_AS_TRUECOPY = factory.getOWLDataProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#datePageCertifiedAsTrueCopy"));

    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#deathCertification
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property WITH_DEATH_CERTIFICATION_STATUS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_WITH_DEATH_CERTIFICATION_STATUS = factory.getOWLDataProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#deathCertification"));

    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#districtDesc
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DISTRICT_DESCIPTION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DISTRICT_DESCIPTION = factory.getOWLDataProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#districtDesc"));

    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#durIllness
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DURATION_OF_ILLNESS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DURATION_OF_ILLNESS = factory.getOWLDataProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#durIllness"));

    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#forename
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property FORENAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_FORENAME = factory.getOWLDataProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#forename"));

    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#hasSource_
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_INFORMATION_SOURCE_.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_INFORMATION_SOURCE_ = factory.getOWLDataProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#hasSource_"));

    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#placeOfDeath
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PLACE_OF_DEATH.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PLACE_OF_DEATH = factory.getOWLDataProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#placeOfDeath"));

    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#quarter
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property QUARTER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_QUARTER = factory.getOWLDataProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#quarter"));

    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#rankDesc
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property RANK.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_RANK = factory.getOWLDataProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#rankDesc"));

    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#sex
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property SEX.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_SEX = factory.getOWLDataProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#sex"));

    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#surname
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property SURNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_SURNAME = factory.getOWLDataProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#surname"));

    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#titleOfReg
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property TITLEOFREG.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_TITLEOFREG = factory.getOWLDataProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#titleOfReg"));

    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#union
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property UNION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_UNION = factory.getOWLDataProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#union"));

    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#volume
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property VOLUME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_VOLUME = factory.getOWLDataProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#volume"));

    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#yearRegistered
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property YEAR_REGISTERED.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_YEAR_REGISTERED = factory.getOWLDataProperty(IRI.create("http://www.IRLontologies.ie/historicalEvents.owl#yearRegistered"));


}
