package com.jbjares.owlmapper.newmodel.to.impl;

import com.jbjares.owlmapper.newmodel.to.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultRank <br>
 * @version generated on Sun Jan 11 02:43:59 GMT 2015 by jbjares
 */
public class DefaultRank extends WrappedIndividualImpl implements Rank {

    public DefaultRank(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#rankPerAtDeath
     */
     
    public Collection<? extends Person> getRank_of_person_at_death() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_RANK_OF_PERSON_AT_DEATH,
                                               DefaultPerson.class);
    }

    public boolean hasRank_of_person_at_death() {
	   return !getRank_of_person_at_death().isEmpty();
    }

    public void addRank_of_person_at_death(Person newRank_of_person_at_death) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_RANK_OF_PERSON_AT_DEATH,
                                       newRank_of_person_at_death);
    }

    public void removeRank_of_person_at_death(Person oldRank_of_person_at_death) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_RANK_OF_PERSON_AT_DEATH,
                                          oldRank_of_person_at_death);
    }


    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#rankDesc
     */
     
    public Collection<? extends Object> getRank() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_RANK, Object.class);
    }

    public boolean hasRank() {
		return !getRank().isEmpty();
    }

    public void addRank(Object newRank) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_RANK, newRank);
    }

    public void removeRank(Object oldRank) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_RANK, oldRank);
    }


}
