package com.jbjares.owlmapper.newmodel.to.impl;

import com.jbjares.owlmapper.newmodel.to.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultMarriage_event <br>
 * @version generated on Sun Jan 11 02:43:59 GMT 2015 by jbjares
 */
public class DefaultMarriage_event extends WrappedIndividualImpl implements Marriage_event {

    public DefaultMarriage_event(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#hasCounty
     */
     
    public Collection<? extends Place> getHas_county() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HAS_COUNTY,
                                               DefaultPlace.class);
    }

    public boolean hasHas_county() {
	   return !getHas_county().isEmpty();
    }

    public void addHas_county(Place newHas_county) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HAS_COUNTY,
                                       newHas_county);
    }

    public void removeHas_county(Place oldHas_county) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HAS_COUNTY,
                                          oldHas_county);
    }


    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#hasInformant_
     */
     
    public Collection<? extends Person> getHas_informant_() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HAS_INFORMANT_,
                                               DefaultPerson.class);
    }

    public boolean hasHas_informant_() {
	   return !getHas_informant_().isEmpty();
    }

    public void addHas_informant_(Person newHas_informant_) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HAS_INFORMANT_,
                                       newHas_informant_);
    }

    public void removeHas_informant_(Person oldHas_informant_) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HAS_INFORMANT_,
                                          oldHas_informant_);
    }


    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#hasRegisterPage
     */
     
    public Collection<? extends Register_page> getHas_register_page() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HAS_REGISTER_PAGE,
                                               DefaultRegister_page.class);
    }

    public boolean hasHas_register_page() {
	   return !getHas_register_page().isEmpty();
    }

    public void addHas_register_page(Register_page newHas_register_page) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HAS_REGISTER_PAGE,
                                       newHas_register_page);
    }

    public void removeHas_register_page(Register_page oldHas_register_page) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HAS_REGISTER_PAGE,
                                          oldHas_register_page);
    }


    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#registeredBy
     */
     
    public Collection<? extends Person> getRegistered_by() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_REGISTERED_BY,
                                               DefaultPerson.class);
    }

    public boolean hasRegistered_by() {
	   return !getRegistered_by().isEmpty();
    }

    public void addRegistered_by(Person newRegistered_by) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_REGISTERED_BY,
                                       newRegistered_by);
    }

    public void removeRegistered_by(Person oldRegistered_by) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_REGISTERED_BY,
                                          oldRegistered_by);
    }


    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/personOntology.owl#OWLObjectPropertyImpl_01420721646860402000
     */
     
    public Collection<? extends District> getHas_district() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HAS_DISTRICT,
                                               DefaultDistrict.class);
    }

    public boolean hasHas_district() {
	   return !getHas_district().isEmpty();
    }

    public void addHas_district(District newHas_district) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HAS_DISTRICT,
                                       newHas_district);
    }

    public void removeHas_district(District oldHas_district) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HAS_DISTRICT,
                                          oldHas_district);
    }


    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#InformantQualification
     */
     
    public Collection<? extends Object> getQualification_of_informant() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_QUALIFICATION_OF_INFORMANT, Object.class);
    }

    public boolean hasQualification_of_informant() {
		return !getQualification_of_informant().isEmpty();
    }

    public void addQualification_of_informant(Object newQualification_of_informant) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_QUALIFICATION_OF_INFORMANT, newQualification_of_informant);
    }

    public void removeQualification_of_informant(Object oldQualification_of_informant) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_QUALIFICATION_OF_INFORMANT, oldQualification_of_informant);
    }


    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#dateOfRegistration
     */
     
    public Collection<? extends Object> getDate_of_registration() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DATE_OF_REGISTRATION, Object.class);
    }

    public boolean hasDate_of_registration() {
		return !getDate_of_registration().isEmpty();
    }

    public void addDate_of_registration(Object newDate_of_registration) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DATE_OF_REGISTRATION, newDate_of_registration);
    }

    public void removeDate_of_registration(Object oldDate_of_registration) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DATE_OF_REGISTRATION, oldDate_of_registration);
    }


    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#deathCertification
     */
     
    public Collection<? extends Object> getWith_death_certification_status() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_WITH_DEATH_CERTIFICATION_STATUS, Object.class);
    }

    public boolean hasWith_death_certification_status() {
		return !getWith_death_certification_status().isEmpty();
    }

    public void addWith_death_certification_status(Object newWith_death_certification_status) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_WITH_DEATH_CERTIFICATION_STATUS, newWith_death_certification_status);
    }

    public void removeWith_death_certification_status(Object oldWith_death_certification_status) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_WITH_DEATH_CERTIFICATION_STATUS, oldWith_death_certification_status);
    }


    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#placeOfDeath
     */
     
    public Collection<? extends Object> getPlace_of_death() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PLACE_OF_DEATH, Object.class);
    }

    public boolean hasPlace_of_death() {
		return !getPlace_of_death().isEmpty();
    }

    public void addPlace_of_death(Object newPlace_of_death) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PLACE_OF_DEATH, newPlace_of_death);
    }

    public void removePlace_of_death(Object oldPlace_of_death) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PLACE_OF_DEATH, oldPlace_of_death);
    }


}
