package com.jbjares.owlmapper.newmodel.to.impl;

import com.jbjares.owlmapper.newmodel.to.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultCause_of_death <br>
 * @version generated on Sun Jan 11 02:43:59 GMT 2015 by jbjares
 */
public class DefaultCause_of_death extends WrappedIndividualImpl implements Cause_of_death {

    public DefaultCause_of_death(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#DeathCauseOf
     */
     
    public Collection<? extends Person> getDeath_cause_of() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_DEATH_CAUSE_OF,
                                               DefaultPerson.class);
    }

    public boolean hasDeath_cause_of() {
	   return !getDeath_cause_of().isEmpty();
    }

    public void addDeath_cause_of(Person newDeath_cause_of) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_DEATH_CAUSE_OF,
                                       newDeath_cause_of);
    }

    public void removeDeath_cause_of(Person oldDeath_cause_of) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_DEATH_CAUSE_OF,
                                          oldDeath_cause_of);
    }


    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#CauseIllnessDuration
     */
     
    public Collection<? extends Object> getCause_of_death_and_duration_of_illness() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CAUSE_OF_DEATH_AND_DURATION_OF_ILLNESS, Object.class);
    }

    public boolean hasCause_of_death_and_duration_of_illness() {
		return !getCause_of_death_and_duration_of_illness().isEmpty();
    }

    public void addCause_of_death_and_duration_of_illness(Object newCause_of_death_and_duration_of_illness) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CAUSE_OF_DEATH_AND_DURATION_OF_ILLNESS, newCause_of_death_and_duration_of_illness);
    }

    public void removeCause_of_death_and_duration_of_illness(Object oldCause_of_death_and_duration_of_illness) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CAUSE_OF_DEATH_AND_DURATION_OF_ILLNESS, oldCause_of_death_and_duration_of_illness);
    }


    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#cause
     */
     
    public Collection<? extends Object> getCause_of_death() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CAUSE_OF_DEATH, Object.class);
    }

    public boolean hasCause_of_death() {
		return !getCause_of_death().isEmpty();
    }

    public void addCause_of_death(Object newCause_of_death) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CAUSE_OF_DEATH, newCause_of_death);
    }

    public void removeCause_of_death(Object oldCause_of_death) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CAUSE_OF_DEATH, oldCause_of_death);
    }


    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#durIllness
     */
     
    public Collection<? extends Object> getDuration_of_illness() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DURATION_OF_ILLNESS, Object.class);
    }

    public boolean hasDuration_of_illness() {
		return !getDuration_of_illness().isEmpty();
    }

    public void addDuration_of_illness(Object newDuration_of_illness) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DURATION_OF_ILLNESS, newDuration_of_illness);
    }

    public void removeDuration_of_illness(Object oldDuration_of_illness) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DURATION_OF_ILLNESS, oldDuration_of_illness);
    }


}
