package com.jbjares.owlmapper.newmodel.to.impl;

import com.jbjares.owlmapper.newmodel.to.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultAddress <br>
 * @version generated on Sun Jan 11 02:43:59 GMT 2015 by jbjares
 */
public class DefaultAddress extends WrappedIndividualImpl implements Address {

    public DefaultAddress(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#countyOf
     */
     
    public Collection<? extends Event> getCounty_of() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_COUNTY_OF,
                                               DefaultEvent.class);
    }

    public boolean hasCounty_of() {
	   return !getCounty_of().isEmpty();
    }

    public void addCounty_of(Event newCounty_of) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_COUNTY_OF,
                                       newCounty_of);
    }

    public void removeCounty_of(Event oldCounty_of) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_COUNTY_OF,
                                          oldCounty_of);
    }


    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#resdOfPerAtDeath
     */
     
    public Collection<? extends Person> getResidence_of_person_at_death() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_RESIDENCE_OF_PERSON_AT_DEATH,
                                               DefaultPerson.class);
    }

    public boolean hasResidence_of_person_at_death() {
	   return !getResidence_of_person_at_death().isEmpty();
    }

    public void addResidence_of_person_at_death(Person newResidence_of_person_at_death) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_RESIDENCE_OF_PERSON_AT_DEATH,
                                       newResidence_of_person_at_death);
    }

    public void removeResidence_of_person_at_death(Person oldResidence_of_person_at_death) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_RESIDENCE_OF_PERSON_AT_DEATH,
                                          oldResidence_of_person_at_death);
    }


    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#resdOfPerInfDeath
     */
     
    public Collection<? extends Person> get_residence_of_Person_Informing_Death() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY__RESIDENCE_OF_PERSON_INFORMING_DEATH,
                                               DefaultPerson.class);
    }

    public boolean has_residence_of_Person_Informing_Death() {
	   return !get_residence_of_Person_Informing_Death().isEmpty();
    }

    public void add_residence_of_Person_Informing_Death(Person new_residence_of_Person_Informing_Death) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY__RESIDENCE_OF_PERSON_INFORMING_DEATH,
                                       new_residence_of_Person_Informing_Death);
    }

    public void remove_residence_of_Person_Informing_Death(Person old_residence_of_Person_Informing_Death) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY__RESIDENCE_OF_PERSON_INFORMING_DEATH,
                                          old_residence_of_Person_Informing_Death);
    }


    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#CountryDesc
     */
     
    public Collection<? extends Object> getCountry_desciption() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_COUNTRY_DESCIPTION, Object.class);
    }

    public boolean hasCountry_desciption() {
		return !getCountry_desciption().isEmpty();
    }

    public void addCountry_desciption(Object newCountry_desciption) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_COUNTRY_DESCIPTION, newCountry_desciption);
    }

    public void removeCountry_desciption(Object oldCountry_desciption) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_COUNTRY_DESCIPTION, oldCountry_desciption);
    }


    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#addressDesc
     */
     
    public Collection<? extends Object> getAddress() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ADDRESS, Object.class);
    }

    public boolean hasAddress() {
		return !getAddress().isEmpty();
    }

    public void addAddress(Object newAddress) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ADDRESS, newAddress);
    }

    public void removeAddress(Object oldAddress) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ADDRESS, oldAddress);
    }


    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#districtDesc
     */
     
    public Collection<? extends Object> getDistrict_desciption() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DISTRICT_DESCIPTION, Object.class);
    }

    public boolean hasDistrict_desciption() {
		return !getDistrict_desciption().isEmpty();
    }

    public void addDistrict_desciption(Object newDistrict_desciption) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DISTRICT_DESCIPTION, newDistrict_desciption);
    }

    public void removeDistrict_desciption(Object oldDistrict_desciption) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DISTRICT_DESCIPTION, oldDistrict_desciption);
    }


}
