package com.jbjares.owlmapper.newmodel.to.impl;

import com.jbjares.owlmapper.newmodel.to.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultPerson <br>
 * @version generated on Sun Jan 11 02:43:59 GMT 2015 by jbjares
 */
public class DefaultPerson extends WrappedIndividualImpl implements Person {

    public DefaultPerson(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#deathIsInfBy
     */
     
    public Collection<? extends Person> getDeath_is_informed_by() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_DEATH_IS_INFORMED_BY,
                                               DefaultPerson.class);
    }

    public boolean hasDeath_is_informed_by() {
	   return !getDeath_is_informed_by().isEmpty();
    }

    public void addDeath_is_informed_by(Person newDeath_is_informed_by) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_DEATH_IS_INFORMED_BY,
                                       newDeath_is_informed_by);
    }

    public void removeDeath_is_informed_by(Person oldDeath_is_informed_by) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_DEATH_IS_INFORMED_BY,
                                          oldDeath_is_informed_by);
    }


    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#hasCauseOfDeath
     */
     
    public Collection<? extends Cause_of_death> getHas_cause_of_death() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HAS_CAUSE_OF_DEATH,
                                               DefaultCause_of_death.class);
    }

    public boolean hasHas_cause_of_death() {
	   return !getHas_cause_of_death().isEmpty();
    }

    public void addHas_cause_of_death(Cause_of_death newHas_cause_of_death) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HAS_CAUSE_OF_DEATH,
                                       newHas_cause_of_death);
    }

    public void removeHas_cause_of_death(Cause_of_death oldHas_cause_of_death) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HAS_CAUSE_OF_DEATH,
                                          oldHas_cause_of_death);
    }


    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#hasDeathRecord
     */
     
    public Collection<? extends Death_event> getHas_death_record() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HAS_DEATH_RECORD,
                                               DefaultDeath_event.class);
    }

    public boolean hasHas_death_record() {
	   return !getHas_death_record().isEmpty();
    }

    public void addHas_death_record(Death_event newHas_death_record) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HAS_DEATH_RECORD,
                                       newHas_death_record);
    }

    public void removeHas_death_record(Death_event oldHas_death_record) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HAS_DEATH_RECORD,
                                          oldHas_death_record);
    }


    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#hasInfDeathOf
     */
     
    public Collection<? extends Person> getHas_informed_the_death_of() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HAS_INFORMED_THE_DEATH_OF,
                                               DefaultPerson.class);
    }

    public boolean hasHas_informed_the_death_of() {
	   return !getHas_informed_the_death_of().isEmpty();
    }

    public void addHas_informed_the_death_of(Person newHas_informed_the_death_of) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HAS_INFORMED_THE_DEATH_OF,
                                       newHas_informed_the_death_of);
    }

    public void removeHas_informed_the_death_of(Person oldHas_informed_the_death_of) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HAS_INFORMED_THE_DEATH_OF,
                                          oldHas_informed_the_death_of);
    }


    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#hasRankAtDeath
     */
     
    public Collection<? extends Rank> getHas_rank_at_death() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HAS_RANK_AT_DEATH,
                                               DefaultRank.class);
    }

    public boolean hasHas_rank_at_death() {
	   return !getHas_rank_at_death().isEmpty();
    }

    public void addHas_rank_at_death(Rank newHas_rank_at_death) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HAS_RANK_AT_DEATH,
                                       newHas_rank_at_death);
    }

    public void removeHas_rank_at_death(Rank oldHas_rank_at_death) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HAS_RANK_AT_DEATH,
                                          oldHas_rank_at_death);
    }


    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#hasRegister
     */
     
    public Collection<? extends Event> getHas_register() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HAS_REGISTER,
                                               DefaultEvent.class);
    }

    public boolean hasHas_register() {
	   return !getHas_register().isEmpty();
    }

    public void addHas_register(Event newHas_register) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HAS_REGISTER,
                                       newHas_register);
    }

    public void removeHas_register(Event oldHas_register) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HAS_REGISTER,
                                          oldHas_register);
    }


    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#hasResdAtDeath
     */
     
    public Collection<? extends Place> getHas_residence_at_death() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HAS_RESIDENCE_AT_DEATH,
                                               DefaultPlace.class);
    }

    public boolean hasHas_residence_at_death() {
	   return !getHas_residence_at_death().isEmpty();
    }

    public void addHas_residence_at_death(Place newHas_residence_at_death) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HAS_RESIDENCE_AT_DEATH,
                                       newHas_residence_at_death);
    }

    public void removeHas_residence_at_death(Place oldHas_residence_at_death) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HAS_RESIDENCE_AT_DEATH,
                                          oldHas_residence_at_death);
    }


    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#hasResdInfDeath
     */
     
    public Collection<? extends Place> getHas_residence_during_Informing_death() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HAS_RESIDENCE_DURING_INFORMING_DEATH,
                                               DefaultPlace.class);
    }

    public boolean hasHas_residence_during_Informing_death() {
	   return !getHas_residence_during_Informing_death().isEmpty();
    }

    public void addHas_residence_during_Informing_death(Place newHas_residence_during_Informing_death) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HAS_RESIDENCE_DURING_INFORMING_DEATH,
                                       newHas_residence_during_Informing_death);
    }

    public void removeHas_residence_during_Informing_death(Place oldHas_residence_during_Informing_death) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HAS_RESIDENCE_DURING_INFORMING_DEATH,
                                          oldHas_residence_during_Informing_death);
    }


    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#hasSigned
     */
     
    public Collection<? extends Register_page> getHas_signed() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HAS_SIGNED,
                                               DefaultRegister_page.class);
    }

    public boolean hasHas_signed() {
	   return !getHas_signed().isEmpty();
    }

    public void addHas_signed(Register_page newHas_signed) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HAS_SIGNED,
                                       newHas_signed);
    }

    public void removeHas_signed(Register_page oldHas_signed) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HAS_SIGNED,
                                          oldHas_signed);
    }


    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/historicalEvents.owl#informs
     */
     
    public Collection<? extends Event> getInforms() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_INFORMS,
                                               DefaultEvent.class);
    }

    public boolean hasInforms() {
	   return !getInforms().isEmpty();
    }

    public void addInforms(Event newInforms) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_INFORMS,
                                       newInforms);
    }

    public void removeInforms(Event oldInforms) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_INFORMS,
                                          oldInforms);
    }


    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/personOntology.owl#OWLObjectPropertyImpl_01420721646860402000
     */
     
    public Collection<? extends District> getHas_district() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HAS_DISTRICT,
                                               DefaultDistrict.class);
    }

    public boolean hasHas_district() {
	   return !getHas_district().isEmpty();
    }

    public void addHas_district(District newHas_district) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HAS_DISTRICT,
                                       newHas_district);
    }

    public void removeHas_district(District oldHas_district) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HAS_DISTRICT,
                                          oldHas_district);
    }


    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/personOntology.owl#OWLObjectPropertyImpl_01420721646871238000
     */
     
    public Collection<? extends Person> getHas_child() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HAS_CHILD,
                                               DefaultPerson.class);
    }

    public boolean hasHas_child() {
	   return !getHas_child().isEmpty();
    }

    public void addHas_child(Person newHas_child) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HAS_CHILD,
                                       newHas_child);
    }

    public void removeHas_child(Person oldHas_child) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HAS_CHILD,
                                          oldHas_child);
    }


    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/personOntology.owl#OWLObjectPropertyImpl_01420721646877197000
     */
     
    public Collection<? extends Person> getHas_husband() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HAS_HUSBAND,
                                               DefaultPerson.class);
    }

    public boolean hasHas_husband() {
	   return !getHas_husband().isEmpty();
    }

    public void addHas_husband(Person newHas_husband) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HAS_HUSBAND,
                                       newHas_husband);
    }

    public void removeHas_husband(Person oldHas_husband) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HAS_HUSBAND,
                                          oldHas_husband);
    }


    /* ***************************************************
     * Object Property http://www.IRLontologies.ie/personOntology.owl#OWLObjectPropertyImpl_01420721646880075000
     */
     
    public Collection<? extends Person> getHas_wife() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HAS_WIFE,
                                               DefaultPerson.class);
    }

    public boolean hasHas_wife() {
	   return !getHas_wife().isEmpty();
    }

    public void addHas_wife(Person newHas_wife) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HAS_WIFE,
                                       newHas_wife);
    }

    public void removeHas_wife(Person oldHas_wife) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HAS_WIFE,
                                          oldHas_wife);
    }


    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#AgeAtLastBirthday
     */
     
    public Collection<? extends Object> getAge_at_last_birthday() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_AGE_AT_LAST_BIRTHDAY, Object.class);
    }

    public boolean hasAge_at_last_birthday() {
		return !getAge_at_last_birthday().isEmpty();
    }

    public void addAge_at_last_birthday(Object newAge_at_last_birthday) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_AGE_AT_LAST_BIRTHDAY, newAge_at_last_birthday);
    }

    public void removeAge_at_last_birthday(Object oldAge_at_last_birthday) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_AGE_AT_LAST_BIRTHDAY, oldAge_at_last_birthday);
    }


    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#CondAtDeath
     */
     
    public Collection<? extends Object> getCondition_at_death() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CONDITION_AT_DEATH, Object.class);
    }

    public boolean hasCondition_at_death() {
		return !getCondition_at_death().isEmpty();
    }

    public void addCondition_at_death(Object newCondition_at_death) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CONDITION_AT_DEATH, newCondition_at_death);
    }

    public void removeCondition_at_death(Object oldCondition_at_death) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CONDITION_AT_DEATH, oldCondition_at_death);
    }


    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#dateOfDeath
     */
     
    public Collection<? extends Object> getDate_of_death() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DATE_OF_DEATH, Object.class);
    }

    public boolean hasDate_of_death() {
		return !getDate_of_death().isEmpty();
    }

    public void addDate_of_death(Object newDate_of_death) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DATE_OF_DEATH, newDate_of_death);
    }

    public void removeDate_of_death(Object oldDate_of_death) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DATE_OF_DEATH, oldDate_of_death);
    }


    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#forename
     */
     
    public Collection<? extends Object> getForename() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FORENAME, Object.class);
    }

    public boolean hasForename() {
		return !getForename().isEmpty();
    }

    public void addForename(Object newForename) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FORENAME, newForename);
    }

    public void removeForename(Object oldForename) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FORENAME, oldForename);
    }


    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#sex
     */
     
    public Collection<? extends Object> getSex() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SEX, Object.class);
    }

    public boolean hasSex() {
		return !getSex().isEmpty();
    }

    public void addSex(Object newSex) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SEX, newSex);
    }

    public void removeSex(Object oldSex) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SEX, oldSex);
    }


    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#surname
     */
     
    public Collection<? extends Object> getSurname() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SURNAME, Object.class);
    }

    public boolean hasSurname() {
		return !getSurname().isEmpty();
    }

    public void addSurname(Object newSurname) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SURNAME, newSurname);
    }

    public void removeSurname(Object oldSurname) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SURNAME, oldSurname);
    }


    /* ***************************************************
     * Data Property http://www.IRLontologies.ie/historicalEvents.owl#titleOfReg
     */
     
    public Collection<? extends Object> getTitleOfReg() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TITLEOFREG, Object.class);
    }

    public boolean hasTitleOfReg() {
		return !getTitleOfReg().isEmpty();
    }

    public void addTitleOfReg(Object newTitleOfReg) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TITLEOFREG, newTitleOfReg);
    }

    public void removeTitleOfReg(Object oldTitleOfReg) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TITLEOFREG, oldTitleOfReg);
    }


}
